### ISSUE TITLE
Wake up latency in cyclic_thread is negative value

### ISSUE THREAD

**Issue by bassamkhamis** [cactusdynamics/cactus-rt#148] opened 2024-11-23 15:06 UTC
I tried to build and run the simple_deadline example on a BeagleBone Black (BBB). The BBB is running a Linux RT kernel, and I got the following output:
```
debian@BeagleBone:~/cactus-rt$ sudo ./build/debug/examples/simple_deadline_example/rt_simple_deadline_example
Testing RT loop for 3600 seconds.
[2024-11-23 14:12:11.960300784][W][ExampleRTThread][cyclic_thread.cc:48] At least 1 loop overrun detected in the last 100: wakeup latency (-576218ns)
+ loop latency (3833ns) > period (10000000ns))
[2024-11-23 14:12:14.730194770][W][ExampleRTThread][cyclic_thread.cc:48] At least 1 loop overrun detected in the last 100: wakeup latency (-4285135432
ns) + loop latency (2791ns) > period (10000000ns))
[2024-11-23 14:12:19.030057174][W][ExampleRTThread][cyclic_thread.cc:48] At least 1 loop overrun detected in the last 100: wakeup latency (-4285156874
ns) + loop latency (16666ns) > period (10000000ns))
[2024-11-23 14:12:23.319888958][W][ExampleRTThread][cyclic_thread.cc:48] At least 1 loop overrun detected in the last 100: wakeup latency (-4285179262
ns) + loop latency (2750ns) > period (10000000ns))
[2024-11-23 14:12:27.619717723][W][ExampleRTThread][cyclic_thread.cc:48] At least 1 loop overrun detected in the last 100: wakeup latency (-4285167472
ns) + loop latency (2917ns) > period (10000000ns))
[2024-11-23 14:12:31.909564968][W][ExampleRTThread][cyclic_thread.cc:48] At least 1 loop overrun detected in the last 100: wakeup latency (-4285155760
ns) + loop latency (3000ns) > period (10000000ns))
[2024-11-23 14:12:36.209412758][W][ExampleRTThread][cyclic_thread.cc:48] At least 1 loop overrun detected in the last 100: wakeup latency (-4285149844
ns) + loop latency (3583ns) > period (10000000ns))  
```
As you can see, `wakeup_latency` holds a negative value, which means  `loop_start` variable is less than `next_wakeup_time_ns` in this statement ` wakeup_latency = loop_start - next_wakeup_time_ns; `, I was expecting to observe some latency since I had previously run rt-tests and measured a maximum latency of approximately 700 µs.

Question: Why is the kernel scheduling this task before its `next_wakeup_time_ns`?

I ran the same example on Ubuntu with the RT kernel and observed the same result (negative values for `wakeup_latency`).

Note: I built the rt kernel for BBB based on [this](https://github.com/RobertCNelson/ti-linux-kernel-dev/tree/5.10.162-ti-rt-r59)

**Comment by shuhaowu** [comment] 2024-11-23 19:27
Yeah the deadline scheduler can be wonky. There is also some other issues I think. Duplicate of #132

**Closed** 2024-11-23 19:27 UTC
